"""add description in room schema

Revision ID: a208666b7e8d
Revises: 8ce1f329be28
Create Date: 2025-08-17 19:25:01.363314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a208666b7e8d'
down_revision: Union[str, Sequence[str], None] = '8ce1f329be28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'rooms', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
